content:
  application/json:
    schema:
      $ref: bblocks://ogc.api.processes.v1.schemas.exception
  text/html:
    schema:
      type: string
description: None of the requested media types is supported at the path.
