content:
  /*:
    schema:
      oneOf:
      - type: string
      - type: number
      - type: integer
      - nullable: true
        type: object
      - type: array
      - type: boolean
      - format: binary
        type: string
      - $ref: bblocks://ogc.api.processes.v1.schemas.results
        description: Negotiate synchronous execution, response=document,any txMode
          and no. outputs
description: Result of synchronous execution
