oneOf:
- $ref: bblocks://ogc.api.processes.v1.schemas.reference
- additionalProperties: false
  properties:
    additionalProperties:
      default: true
      oneOf:
      - $ref: bblocks://ogc.api.processes.v1.schemas.schema
      - $ref: bblocks://ogc.api.processes.v1.schemas.reference
      - type: boolean
    allOf:
      items:
        oneOf:
        - $ref: bblocks://ogc.api.processes.v1.schemas.schema
        - $ref: bblocks://ogc.api.processes.v1.schemas.reference
      type: array
    anyOf:
      items:
        oneOf:
        - $ref: bblocks://ogc.api.processes.v1.schemas.schema
        - $ref: bblocks://ogc.api.processes.v1.schemas.reference
      type: array
    contentEncoding:
      type: string
    contentMediaType:
      type: string
    contentSchema:
      type: string
    default: {}
    deprecated:
      default: false
      type: boolean
    description:
      type: string
    enum:
      items: {}
      minItems: 1
      type: array
      uniqueItems: false
    example: {}
    exclusiveMaximum:
      default: false
      type: boolean
    exclusiveMinimum:
      default: false
      type: boolean
    format:
      type: string
    items:
      oneOf:
      - $ref: bblocks://ogc.api.processes.v1.schemas.schema
      - $ref: bblocks://ogc.api.processes.v1.schemas.reference
    maxItems:
      minimum: 0
      type: integer
    maxLength:
      minimum: 0
      type: integer
    maxProperties:
      minimum: 0
      type: integer
    maximum:
      type: number
    minItems:
      default: 0
      minimum: 0
      type: integer
    minLength:
      default: 0
      minimum: 0
      type: integer
    minProperties:
      default: 0
      minimum: 0
      type: integer
    minimum:
      type: number
    multipleOf:
      exclusiveMinimum: 0
      type: number
    not:
      oneOf:
      - $ref: bblocks://ogc.api.processes.v1.schemas.schema
      - $ref: bblocks://ogc.api.processes.v1.schemas.reference
    nullable:
      default: false
      type: boolean
    oneOf:
      items:
        oneOf:
        - $ref: bblocks://ogc.api.processes.v1.schemas.schema
        - $ref: bblocks://ogc.api.processes.v1.schemas.reference
      type: array
    pattern:
      format: regex
      type: string
    properties:
      additionalProperties:
        oneOf:
        - $ref: bblocks://ogc.api.processes.v1.schemas.schema
        - $ref: bblocks://ogc.api.processes.v1.schemas.reference
      type: object
    readOnly:
      default: false
      type: boolean
    required:
      items:
        type: string
      minItems: 1
      type: array
      uniqueItems: true
    title:
      type: string
    type:
      enum:
      - array
      - boolean
      - integer
      - number
      - object
      - string
      type: string
    uniqueItems:
      default: false
      type: boolean
    writeOnly:
      default: false
      type: boolean
  type: object
