$comment: Adapted from https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/landingPage.yaml
type: object
required:
  - links
properties:
  title:
    type: string
    example: Buildings in Bonn
  description:
    type: string
    example: Access to data about buildings in the city of Bonn via a Web API that conforms to the OGC API Features specification.
  links:
    type: array
    items:
      $ref: bblocks://ogc.ogc-utils.json-link
