allOf:
- $ref: bblocks://ogc.api.processes.v1.schemas.processSummary
- properties:
    inputs:
      additionalProperties:
        $ref: bblocks://ogc.api.processes.v1.schemas.swagger.inputDescription
    outputs:
      additionalProperties:
        $ref: bblocks://ogc.api.processes.v1.schemas.swagger.outputDescription
  type: object
