description: 'Optional URIs for callbacks for this job.


  Support for this parameter is not required and the parameter may be

  removed from the API definition, if conformance class **''callback''**

  is not listed in the conformance declaration under `/conformance`.'
properties:
  failedUri:
    format: uri
    type: string
  inProgressUri:
    format: uri
    type: string
  successUri:
    format: uri
    type: string
required:
- successUrl
type: object
