$comment: Adapted from https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collections.yaml
type: object
properties:
  links:
    type: array
    items:
      $ref: bblocks://ogc.ogc-utils.json-link
  collections:
    type: array
    items:
      $ref: bblocks://ogc.api.features.v1.schemas.collection