content:
  application/json:
    schema:
      $ref: bblocks://ogc.api.processes.v1.schemas.landingPage
  text/html:
    schema:
      type: string
description: 'The landing page provides links to the API definition

  (link relations `service-desc` and `service-doc`),

  the Conformance declaration (path `/conformance`,

  link relation `http://www.opengis.net/def/rel/ogc/1.0/conformance`), and to other
  resources.'
