content:
  application/json:
    example:
      conformsTo:
      - http://www.opengis.net/spec/ogcapi-processes/1.0/conf/core
    schema:
      $ref: bblocks://ogc.api.processes.v1.schemas.confClasses
  text/html:
    schema:
      type: string
description: 'The URIs of all conformance classes supported by the server.


  To support "generic" clients that want to access multiple

  OGC API - Processes implementations - and not "just" a specific

  API / server, the server declares the conformance

  classes it implements and conforms to.'
